import type { GetServerSidePropsContext, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Text, Flex, Grid, Tag } from "sore-ui";
import useSWR from 'swr';
import { API_URL } from '@/config/api';
import fetcher from '@/config/fetcher';
import Card from '@/components/Card';
import { useRouter } from 'next/router';

const API = `${API_URL}/quotes`

interface Quote {
  count: number
  // The total number of quotes matching this query
  totalCount: number
  // The current page number
  page: number
  // The total number of pages matching this request
  totalPages: number
  // The 1-based index of the last result included in the current response.
  lastItemIndex: number
  // The array of quotes
  results: Array<{
    _id: string
    // The quotation text
    content: string
    // The full name of the author
    author: string
    // The `slug` of the quote author
    authorSlug: string
    // The length of quote (number of characters)
    length: number
    // An array of tag names for this quote
    tags: string[]
  }>
}

interface TagPageProps {
  quotes: Quote,
}

const Tag: NextPage<TagPageProps> = ({ quotes,  ...props}) => {
  const router = useRouter();
  const { tag }: { tag?: string } = router.query;

  const renderQuote = () => {
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Your daily quote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text size="5xl" weight="600" my={4} >Tag: {tag}</Text>

      <Flex minHeight="calc(100vh - 150px)" direction="column" px="3rem" m="auto">
        <Grid column="repeat(4, 1fr)" gap="16px">
          {quotes.results.map(quote => (
            <Card key={quote._id}>
              <Text size="lg" mb="16px">&quot;{quote.content}&quot;</Text>
              <Text color="cool-gray-500">{quote.author}</Text>
            </Card>
          ))}
        </Grid>
      </Flex>
      <Text textAlign="center" py="20px">
        Quotes from <a href="https://github.com/lukePeavey/quotable">
          <Text as="span" color="blue-500">quotable.io
            </Text>
          </a>
      </Text>
    </div>
  )
}

export async function getServerSideProps({ query  }: GetServerSidePropsContext) {
  const quotes = await fetcher(`${API}?tags=${query.tag}`)

  return {
    props: {
      quotes,
    }
  }
}

export default Tag
