import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// @ts-ignore
import { Text, Flex, Divider, Tag } from "sore-ui";
import useSWR from 'swr';
import { API_URL } from '@/config/api';
import Link from 'next/link';

const Home: NextPage = () => {
  const { data, error } = useSWR(`${API_URL}/random`);

  const onClickQuote = (quote: string) => {
    navigator.clipboard.writeText(`"${quote}"`);
  }

  const renderQuote = () => {
    if (!data) {
      return <Text size="h1">...</Text>
    }

    return (
      <Flex mx="auto" direction="column">
        <Text textAlign="center" as="h1" size="6xl" onClick={() => onClickQuote(data.content)}>&quot;{data.content}&quot;</Text>
        <Flex m="auto" direction="column" w="325px">
          <Divider />
          <Text textAlign="center" color="cool-gray-500" mb="15px">{data.author}</Text>
          <Flex justify="center" flexWrap="wrap" spaceX="4px">
            {data.tags.map((tag: string) => (
              <Link passHref key={tag} href={`/${tag}`}>
                <a>
                  <Tag>{tag}</Tag>
                </a>
              </Link>
            ))}
          </Flex>
        </Flex>
      </Flex>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Your daily quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex minHeight="calc(100vh - 60px)" align="center" justify="center" direction="column" px="3rem" m="auto">
        {renderQuote()}
      </Flex>
      <Text textAlign="center" py="20px">
        Quotes from <a href="https://github.com/lukePeavey/quotable">
          <Text as="span" color="blue-500">quotable.io
            </Text>
          </a>
      </Text>
    </div>
  )
}

export default Home
